# Generated by Django 2.2.11 on 2020-03-12 05:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ***REMOVED***

    operations = [
        migrations.CreateModel(
            name='DoctorProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_Personal_name', models.CharField(max_length=264)),
                ('Doctor_experience', models.PositiveSmallIntegerField()),
                ('Doctor_Education', models.CharField(max_length=264)),
                ('Doctor_Speciality', models.CharField(max_length=264)),
                ('Hospital_Address', models.CharField(max_length=300)),
                ('Hospital_Pin', models.PositiveIntegerField()),
                ('Hospital_State', models.CharField(max_length=100)),
                ('Doctor_Certificate', models.FileField(upload_to='Certificate')),
                ('Doctor_Photo', models.ImageField(upload_to='Doctor_Pic')),
                ('is_patient', models.BooleanField(default=False)),
                ('is_doctor', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ***REMOVED***,
        ),
        migrations.CreateModel(
            name='RecordInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Personal_name', models.CharField(max_length=264)),
                ('Appointment_Date', models.DateField(default=datetime.date.today, verbose_name='Apointment_Date')),
                ('Disease', models.CharField(max_length=264)),
                ('Medicine_Prescription', models.CharField(max_length=400)),
                ('Report_Name', models.CharField(max_length=264)),
                ('Report_Document', models.FileField(blank=True, upload_to='media/Patient_Report')),
                ('Doctor_Personal_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medi_app2.DoctorProfileInfo')),
            ***REMOVED***,
        ),
        migrations.CreateModel(
            name='PatientProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Personal_name', models.CharField(max_length=264)),
                ('Patient_Age', models.PositiveSmallIntegerField()),
                ('Patient_Address', models.CharField(max_length=300)),
                ('Patient_Pin', models.PositiveIntegerField()),
                ('Patient_State', models.CharField(max_length=100)),
                ('is_patient', models.BooleanField(default=True)),
                ('is_doctor', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ***REMOVED***,
        ),
        migrations.CreateModel(
            name='LabInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Person_name', models.CharField(max_length=264)),
                ('Address', models.CharField(max_length=264)),
                ('Pincode', models.PositiveIntegerField()),
                ('Lab_Certificate', models.FileField(upload_to='media/lab_Certificate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ***REMOVED***,
        ),
    ***REMOVED***
